apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nkendyal-poi-gateway-app-dev
  annotations:
    argocd/app-name: nkendyal-poi-gateway-app-dev
    backstage.io/kubernetes-id: nkendyal-poi-gateway-app
    backstage.io/kubernetes-namespace: nkendyal
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-air/nkendyal-gateway
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.r9m8ttn9.eastus2.aroapp.io/dev-pipelines/ns/nkendyal/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.r9m8ttn9.eastus2.aroapp.io/k8s/ns/nkendyal/deployments/nkendyal-poi-gateway-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.r9m8ttn9.eastus2.aroapp.io/#https://github.com/rhdh-air/nkendyal-gateway?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/nkendyal"
  system: workshop-system-nkendyal
  providesApis:
    - gateway-api-nkendyal
  consumesApis:
    - backend-api-nkendyal
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-nkendyal
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/nkendyal"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: gateway-api-nkendyal
  description: API surface exposed to interact with Backends (summit POIs + parks data) via the Gateway
  links:
    - url: http://nkendyal-poi-gateway-app-nkendyal.apps.r9m8ttn9.eastus2.aroapp.io/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://github.com/rhdh-air/nkendyal-gateway/tree/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "user:default/nkendyal"
  system: workshop-system-nkendyal
  definition:
    $text: https://github.com/rhdh-air/nkendyal-gateway/tree/main/src/main/resources/META-INF/openapi.yaml
